This dataset contains data of airplane accidents involving civil, commercial and military transport worldwide from 1908-09-17 to 2009-06-08.

# Data Cleaning

In [3]:
import pandas as pd

In [5]:
# Loading Data
data = pd.read_csv('dataset.csv')
data.head(50)

,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,07/12/1912,06:30,"AtlantiCity, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
2,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,-,NaN,Curtiss seaplane,NaN,NaN,1.0,1.0,0.0,The first fatal airplane accident in Canada oc...
3,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,14.0,0.0,The airship flew into a thunderstorm and encou...
4,10/17/1913,10:30,"Near Johannisthal, Germany",Military - German Navy,NaN,NaN,Zeppelin L-2 (airship),NaN,NaN,30.0,30.0,0.0,Hydrogen gas which was being vented was sucked...
5,03/05/1915,01:00,"Tienen, Belgium",Military - German Navy,NaN,NaN,Zeppelin L-8 (airship),NaN,NaN,41.0,21.0,0.0,Crashed into trees while attempting to land af...
6,09/03/1915,15:20,"Off Cuxhaven, Germany",Military - German Navy,NaN,NaN,Zeppelin L-10 (airship),NaN,NaN,19.0,19.0,0.0,"Exploded and burned near Neuwerk Island, when..."
7,07/28/1916,NaN,"Near Jambol, Bulgeria",Military - German Army,NaN,NaN,Schutte-Lanz S-L-10 (airship),NaN,NaN,20.0,20.0,0.0,"Crashed near the Black Sea, cause unknown."
8,09/24/1916,01:00,"Billericay, England",Military - German Navy,NaN,NaN,Zeppelin L-32 (airship),NaN,NaN,22.0,22.0,0.0,Shot down by British aircraft crashing in flames.
9,10/01/1916,23:45,"Potters Bar, England",Military - German Navy,NaN,NaN,Zeppelin L-31 (airship),NaN,NaN,19.0,19.0,0.0,Shot down in flames by the British 39th Home D...
10,11/21/1916,NaN,"Mainz, Germany",Military - German Army,NaN,NaN,Super Zeppelin (airship),NaN,NaN,28.0,27.0,0.0,Crashed in a storm.
11,11/28/1916,23:45,"Off West Hartlepool, England",Military - German Navy,NaN,NaN,Zeppelin L-34 (airship),NaN,NaN,20.0,20.0,0.0,Shot down by British anti-aircraft fire and ai...
12,03/04/1917,NaN,"Near Gent, Belgium",Military - German Army,NaN,NaN,Airship,NaN,NaN,20.0,20.0,0.0,Caught fire and crashed.
13,03/30/1917,NaN,Off Northern Germany,Military - German Navy,NaN,NaN,Schutte-Lanz S-L-9 (airship),NaN,NaN,23.0,23.0,0.0,Struck by lightning and crashed into the Balti...
14,05/14/1917,05:15,"Near Texel Island, North Sea",Military - German Navy,NaN,NaN,Zeppelin L-22 (airship),NaN,NaN,21.0,21.0,0.0,"Crashed into the sea from an altitude of 3,000..."
15,06/14/1917,08:45,"Off Vlieland Island, North Sea",Military - German Navy,NaN,NaN,Zeppelin L-43 (airship),NaN,NaN,24.0,24.0,0.0,Shot down by British aircraft.
16,08/21/1917,07:00,Off western Denmark,Military - German Navy,NaN,NaN,Zeppelin L-23 (airship),NaN,NaN,18.0,18.0,0.0,Shot down by British aircraft.
17,10/20/1917,07:45,"Near Luneville, France",Military - German Navy,NaN,NaN,Zeppelin L-44 (airship),NaN,NaN,18.0,18.0,0.0,Shot down by French anti-aircraft fire.
18,04/07/1918,21:30,Over the Mediterranean,Military - German Navy,NaN,NaN,Zeppelin L-59 (airship),NaN,NaN,23.0,23.0,0.0,Exploded and crashed into the sea off the sout...
19,05/10/1918,NaN,"Off Helgoland Island, Germany",Military - German Navy,NaN,NaN,Zeppelin L-70 (airship),NaN,NaN,22.0,22.0,0.0,Shot down by British aircraft crashing from a ...
20,08/11/1918,10:00,"Ameland Island, North Sea",Military - German Navy,NaN,NaN,Zeppelin L-53 (airship),NaN,NaN,19.0,19.0,0.0,Shot down by british aircraft.
21,12/16/1918,NaN,"Elizabeth, New Jersey",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,97,NaN,1.0,1.0,0.0,NaN
22,05/25/1919,NaN,"Cleveland, Ohio",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,61,NaN,1.0,1.0,0.0,Caught fire in midair. The pilot leaped from t...
23,07/19/1919,NaN,"Dix Run, Pennsylvania",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,82,NaN,1.0,1.0,0.0,NaN
24,10/02/1919,NaN,"Newcastle, England",Aircraft Transport and Travel,NaN,NaN,De Havilland DH-4,NaN,NaN,1.0,1.0,0.0,NaN
25,10/14/1919,NaN,"Cantonsville, Maryland",US Aerial Mail Service,NaN,NaN,Curtiss R-4LM,32,NaN,1.0,1.0,0.0,NaN
26,10/20/1919,NaN,English Channel,Aircraft Transport and Travel,NaN,NaN,De Havilland DH-4,G-EAHG,NaN,NaN,NaN,NaN,NaN
27,10/30/1919,NaN,"Long Valley, New Jersey",US Aerial Mail Service,NaN,NaN,De Havilland DH.4,77,NaN,1.0,1.0,0.0,NaN
28,03/10/1920,NaN,"New Paris, Indiana",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,65,NaN,1.0,1.0,0.0,NaN
29,03/30/1920,NaN,"Newark, New Jersey",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,72,NaN,1.0,1.0,0.0,NaN
30,04/10/1920,NaN,"Newark, New Jersey",US Aerial Mail Service,NaN,NaN,Curtiss R-4LM,49,NaN,2.0,1.0,0.0,NaN
31,04/11/1920,NaN,"Heller Field, New Jersey",US Aerial Mail Service,NaN,NaN,Curtiss JN-4H,44,NaN,2.0,1.0,0.0,NaN
32,05/12/1920,NaN,"Oskaloosa, Iowa",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,79,NaN,2.0,1.0,0.0,NaN
33,06/06/1920,NaN,"Cleveland, Ohio",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,204,NaN,1.0,1.0,0.0,NaN
34,08/16/1920,NaN,"Bedford, England",By Air,NaN,NaN,Armstrong-Whitworth F-K-8,G-EALW,NaN,1.0,1.0,0.0,NaN
35,08/16/1920,NaN,"College Park, Maryland",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,317,NaN,1.0,1.0,0.0,NaN
36,09/01/1920,NaN,"Morristown, New Jersey",US Aerial Mail Service,NaN,NaN,Junkers JL-6,305,NaN,2.0,2.0,0.0,NaN
37,09/15/1920,NaN,"Pemberville, Ohio",US Aerial Mail Service,NaN,NaN,Junkers F-13,308,NaN,2.0,2.0,0.0,NaN
38,09/27/1920,NaN,"Hillersburg, Pennsylvania",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,316,NaN,1.0,1.0,0.0,NaN
39,10/02/1920,NaN,"Off Port Vendres, France",Latecoere Airlines,NaN,NaN,Salmson 2-A-2,F-ALAI,31,2.0,2.0,0.0,NaN
40,10/05/1920,NaN,"Valencia, Spain",Latecoere Airlines,NaN,NaN,Breguet 14,F-ALTA,20,2.0,2.0,0.0,Crashed while landing.
41,10/15/1920,NaN,"Batavia, Illinois",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,76,NaN,1.0,1.0,0.0,NaN
42,11/07/1920,NaN,"Tie Siding, Wyoming",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,NaN,178,1.0,1.0,0.0,NaN
43,12/14/1920,NaN,"Cricklewood, England",Handley Page Transport,NaN,NaN,Handley Page HP-16,G-EAMA,HP-25,8.0,4.0,0.0,Crashed into a tree on take off in fog.
44,12/24/1920,NaN,"Barcelona, Spain",Aeropostale,NaN,NaN,Breguet 14,F-ALBO,NaN,1.0,1.0,0.0,NaN
45,02/03/1921,NaN,"Mendotta, Minnisota",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,130,NaN,1.0,1.0,0.0,NaN
46,02/09/1921,NaN,"La Crosse, Wisconsin",US Aerial Mail Service,NaN,NaN,Junkers F-13,301,NaN,3.0,3.0,0.0,NaN
47,02/15/1921,NaN,Off Gibraltar,Aeropostale,NaN,NaN,Breguet 14,F-ALBA,NaN,2.0,2.0,0.0,NaN
48,02/22/1921,NaN,"Elko, Nevada",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,67,NaN,1.0,1.0,0.0,NaN
49,04/06/1921,NaN,"Point Cook, Australia",Military - Royal Australian Air Force,NaN,NaN,NaN,H3021,NaN,2.0,1.0,0.0,NaN

In [4]:
# Data information (number of non-null values and data type)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5268 entries, 0 to 5267
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          5268 non-null   object
 1   Time          3049 non-null   object
 2   Location      5248 non-null   object
 3   Operator      5250 non-null   object
 4   Flight #      1069 non-null   object
 5   Route         3562 non-null   object
 6   Type          5241 non-null   object
 7   Registration  4933 non-null   object
 8   cn/In         4040 non-null   object
 9   Aboard        5246 non-null   float64
 10  Fatalities    5256 non-null   float64
 11  Ground        5246 non-null   float64
 12  Summary       4878 non-null   object
dtypes: float64(3), object(10)
memory usage: 535.2+ KB

In [6]:
len(data)

5268